apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: schemas-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: _schemas
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
    retention.ms: 7200000
    segment.bytes: 1073741824
