apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  labels:
    strimzi.io/cluster: my-affinity-cluster-2
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-affinity-cluster-2
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.9.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: strimzi.io/node-pool
                      operator: In
                      values:
                        - pool-a
                 # Broker 1 in pool-b
                - matchExpressions:
                    - key: strimzi.io/node-pool
                      operator: In
                      values:
                        - pool-a
                  # Broker 2 in pool-c
                - matchExpressions:
                    - key: strimzi.io/node-pool
                      operator: In
                      values:
                        - pool-a
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                # Zookeeper 0 in pool-a
                - matchExpressions:
                    - key: strimzi.io/node-pool
                      operator: In
                      values:
                        - pool-a
                # Zookeeper 1 in pool-b
                - matchExpressions:
                    - key: strimzi.io/node-pool
                      operator: In
                      values:
                        - pool-a
                # Zookeeper 2 in pool-c
                - matchExpressions:
                    - key: strimzi.io/node-pool
                      operator: In
                      values:
                        - pool-a
  entityOperator:
    topicOperator: {}
    userOperator: {}
